name: flutter_daemon_example
description: "Demonstrates how to use the flutter_daemon plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_daemon:
    path: ../

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  http: ^1.3.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true